### ISSUE TITLE
Incorrect password for docker

### ISSUE THREAD

**Issue by JohnEmhoff** [elasticluster/elasticluster#677]
I get this from a fresh download of elasticluster --

```
$ ./elasticluster.sh list-templates     
Unable to find image 'riccardomurri/elasticluster:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/riccardomurri/elasticluster/manifests/latest: unauthorized: incorrect username or password.
See 'docker run --help'.
```

Is that expected? I don't see any relevant config in the docs; apologies if I missed something.

**Comment by riccardomurri** [comment]
Definitely not expected - but I didn't change anything in the Docker-related settings lately, so I suspect this might be something on Docker's side.

I don't have time to dig deeper now, will try to do tomorrow.

**Comment by riccardomurri** [comment]
I cannot reproduce the issue from a Ubuntu 18.04 VM just started on Google Cloud.

However, what I had to do in order to get the quickstart running was the following:

    sudo systemctl restart docker
    sudo usermod -aG docker $USER

Otherwise I would get connection errors to the Docker daemon.

**Comment by JohnEmhoff** [comment]
Thanks for looking into it -- I wiped docker from my system and installed the latest, and everything seems to work now. Sorry to waste your time!

**Comment by riccardomurri** [comment]
Glad to know all ended well :-)  Please don't feel sorry!  It's actually difficult for me to test things from a user's perspective, and to keep up with all changes on the 3rd party platforms ElastiCluster depends on (Docker, in this case), so issues like this are actually very valuable because they provide insight into what is a blind spot for me ;-) So please keep reporting!
