### ISSUE TITLE
authentication error while resizing

### ISSUE THREAD

**Issue by naryou** [elasticluster/elasticluster#727]
Hi Riccardo,

I have a local cluster out of S3IT cloud and I want to downsize it. I have done resizing several times over the last few years but now I'm getting an authentication error. Below are my commands and the error I get. I appreciate your comment on it.

Thank you so much in advance,

Cheers,
Narcis

***
elasticluster --pull
elasticluster resize -r 1:computeGPU,2:med32compute,2:med64compute,1:med128Lcompute,2:med128compute -t primrose primrose
Version 2 is deprecated, use alternative version 3 instead.
2023-10-25 07:37:46 f32a64338cb7 elasticluster[1] ERROR Error: The request you have made requires authentication. (HTTP 401) (Request-ID: req-1ac3b871-1de9-4b29-a9a3-8be3bfb38c10)
Aborting because of errors: The request you have made requires authentication. (HTTP 401) (Request-ID: req-1ac3b871-1de9-4b29-a9a3-8be3bfb38c10).
***

**Comment by riccardomurri** [comment]
Hello @naryou 

I have left UZH since a few years now; I'm not sure what has changed on Science Cloud and what the current authentication procedure is.  Asking the S3IT helpdesk might be a better option :-)

Cheers,
Riccardo

P.S. If you find out, it would be great if you could post the solution here so that others can eventually profit. Thanks!
